keys:
  - &mikilio E12CB38E6FC75F203B973FE8C1FD5ADC93DB2220
  - &workstation age1w2dzk2a9ccrgjk4hxa539xu2mm53yjps4ll9rfdqenytr3a2epjqvwcs60
  - &homeserver age1cf48ggh87r9gy3r03l8mjp5gyd5v8r53c543u59mnuq8lctmlspsvs5uyu
  - &elitebook age1rr50xgnm3s0w956vgtu5qjjtxf9nke48wmxuh287eamv2ym03v0sla6hhz

creation_rules:
  #----------------Users--------------------------
  - path_regex: secrets/user/mikilio.yaml
    key_groups:
    - pgp:
      - *mikilio
  #----------------Hosts--------------------------
  - path_regex: secrets/hosts/workstation.yaml
    key_groups:
    - age:
      - *workstation
      pgp:
      - *mikilio
  - path_regex: secrets/hosts/homeserver.yaml
    key_groups:
    - age:
      - *homeserver
      pgp:
      - *mikilio
  - path_regex: secrets/hosts/elitebook.yaml
    key_groups:
    - age:
      - *elitebook
      pgp:
      - *mikilio

