[[env]]
name = "sopsCreateGPGHome"
value = true

[[env]]
name = "sopsPGPKeyDirs"
value = "secrets/keys/hosts secrets/keys/users"

[[commands]]
name = "getgpg"
help = "Use admin keys instead of user keyring"
category = "scripts"
command = "source './scripts/importGPGKeys.sh'"

[[commands]]
name = "preinstall"
help = "Install nixos to available drives"
category = "scripts"
command = "source './scripts/prepare-nixos.sh'"

[[commands]]
name = "regu2f"
help = "Register a new FIDO2 key handle"
category = "scripts"
command = "source './scripts/register_pam_u2f.sh'"

[[commands]]
category = "programs"
package = "sops"

[devshell]
packages = [
  "gnupg",
  "coreutils",
  "parted",
  "nixos-install-tools",
  "alejandra",
]
