[[env]]
name = "sopsCreateGPGHome"
value = true

[[env]]
name = "sopsPGPKeyDirs"
value = "secrets/keys/hosts secrets/keys/users"

[[commands]]
name = "getadmingpg"
help = "Use admin keys instead of user keyring (currently broken)"
category = "scripts"
command = "source './scripts/importGPGKeys.sh'"

[[commands]]
name = "hms"
help = "Switch to this home-manager configuration"
category = "scripts"
command = "nix run . -- switch"

[[commands]]
name = "preinstall"
help = "Install nixos to available drives"
category = "scripts"
command = "source './scripts/prepare-nixos.sh'"

[[commands]]
category = "programs"
package = "sops"

[devshell]
packages = [
  "gnupg",
  "coreutils",
  "parted",
  "dosfstools",
  "nixos-install-tools",
  "alejandra",
]
